### ISSUE TITLE
ClientData.Character can be null on PlayerJoined

### ISSUE THREAD

**Issue by NikoCat233** [Next-Fast/NextChat#2]
https://github.com/Next-Fast/NextChat/blob/c16ce7b577ad4e7443c653e75fde8c890ddad5cf/Next_Chat/Patches/PlayerPatch.cs#L14

Patch PlayerControl.Awake instead, remember to patch postfix and make sure postfix only run once

**Comment by TianMengLucky** [comment]
之前试过，好像因为一些原因才改成现在这样
